[Interface]
PrivateKey = QH+VpH7P7L6ojSHJNnJNl1mK9SiLN2b+LRqWPwe350g=
Address = 10.88.0.1/24
ListenPort = 51820
MTU = 1420
PostUp = iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT
PostDown = iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE; iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT

[Peer]
# pc-client
PublicKey = eQhbT2Zir6L/wUopUTVA7Te8OQtg8PMuJ1gUs7ofDz0=
PresharedKey = dWCTQ3vn0M2nl1llE3JRuisAW4OXid8HVILsOTkQ0io=
AllowedIPs = 10.88.0.2/32
