[Interface]
PrivateKey = MGfWue3XV/XmBgrBFOeMqL9PyIHEkpf67938L3tO+EM=
Address = 10.88.0.1/24
ListenPort = 51820
MTU = 1420
PostUp = iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT
PostDown = iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE; iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT

[Peer]
# pc-client
PublicKey = 2B0z2qUAxhf2CUa+xHW1FvS4j61qKZ6ttCeUm2HZjgk=
PresharedKey = FH/0LCcEAy9lZXwj0nP6WHkHB+ARWglrGJ19d9mrr5M=
AllowedIPs = 10.88.0.2/32

[Peer]
# phone-client
PublicKey = lYl/6oWssIXcVbwzwnNQ6SAj3aSt/F8NV+7oOI00vmc=
PresharedKey = Hcai9cNAEGQZkKxoksrOl5yexw5kIhXz2f3sYC3aiPI=
AllowedIPs = 10.88.0.3/32
